version: "3.8"
networks:
  postgresql-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"

services:
  postgresql:
    image: postgres:13.0
    ports:
      - "5432:5432"
    container_name: "dockerpostgresql"
    networks:
      - postgresql-network
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
    expose:
      - '5432'
  golang:
    build:
      context: .
      dockerfile: dockerfile
    container_name: "docker-golang"
    networks:
      - postgresql-network
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: always
    command: air -c .air.toml
  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - postgresql-network
    environment:
      - PGADMIN_DEFAULT_EMAIL=matheus.giordanioliveira@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=senha
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 4000:80
    links:
      - postgresql
    

volumes:
  pgadmin_data:
  postgres_data: