version: "3.8"
networks:
  postgresql-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"

services:
  postgresql:
    image: postgres:13.0
    ports:
      - "5432:5432"
    container_name: "dockerpostgresql"
    networks:
      - postgresql-network
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
    expose:
      - '5432'
  golang:
    build:
      context: .
      dockerfile: dockerfile
    container_name: "docker-golang"
    networks:
      - postgresql-network
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: go run main.go
    